name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    uses: ./.github/workflows/_test.yml
    with:
      run-e2e: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

  build-desktop:
    name: Desktop
    needs: test
    uses: ./.github/workflows/_build-desktop.yml
    secrets: inherit

  build-mobile:
    name: Mobile
    needs: test
    uses: ./.github/workflows/_build-mobile.yml
    secrets: inherit
    with:
      platform: both
